version: '3'
services:
  mysql:
    image: mysql:8.0.23
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: cuidapet
      MYSQL_DATABASE: cuidapet_db
      MYSQL_USER: gabrielMenoi
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ../mysql_data:/var/lib/mysql
